### ISSUE TITLE
一个简单的makefile | Ykk

### ISSUE THREAD

**Issue by ykk648** [ykk648/ykk648.github.io#151]
https://ykksmile.top/posts/30483/

**Comment by xidianleeloo** [comment]
我也想搭建一个这样的博客，可以教教我吗




At 2018-06-07 15:38:01, "Tyler Luan" <notifications@github.com> wrote:


https://ykksmile.top/posts/30483/

**Comment by cloisonne** [comment]
先去hexo官网  把hexo搭起来  然后把github pages搞明白   然后再找一些主题就可以了
