### ISSUE TITLE
关于我&留言板 | Ykk's blog

### ISSUE THREAD

**Issue by ykk648** [ykk648/ykk648.github.io#3]
http://ykksmile.top/about/

**Comment by xidianleeloo** [comment]
厉害了

**Comment by cloisonne** [comment]
@xidianleeloo 啊哈哈

**Comment by cloisonne** [comment]
@xidianleeloo 我看你folk了我的pages的库  如果你想自己搭建一个 需要folk主题 自己搭建本机的环境（比如hexo  

这是我博客主题的原作者https://github.com/cloisonne/hexo-theme-yelee 但已经很久不更新了

如果想用我现在的主题 我可以发给你
